version: '3.8'

services:
  tg-bot:
    build: '.'
    volumes:
      - ./Databases:/app/Databases
      - ./LogsBot:/app/LogsBot
    restart: unless-stopped

  redis:
    image: redis:7.2.1-alpine3.18
    restart: unless-stopped
    expose:
      - 6379