name: Test build and deploy DEMO

on:
  push:
    branches: [ "demo" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test build
      run: docker compose build 
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy      
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ vars.SSH_HOST }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        port: ${{ vars.SSH_PORT }}
        username: ${{ vars.SSH_USER }}
        script_stop: true
        script: |
          cd ${{ vars.PATH_TO_DEMO_PROJECT_FOLDER }}
          git checkout demo
          git pull
          docker compose up -d --build
