name: Test build and deploy project

on:
  push:
    branches: [ "work" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test build
      uses: whoan/docker-build-with-cache-action@v6
      with: 
        dockerfile: Dockerfile
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy      
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ vars.SSH_HOST }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        port: ${{ vars.SSH_PORT }}
        username: ${{ vars.SSH_USER }}
        script_stop: true
        script: |
          cd ${{ vars.PATH_TO_PROJECT_FOLDER }}
          docker compose stop
          git checkout work
          git pull origin work
          docker compose up -d --build
